# -*- coding: utf-8 -*-
"""Jokenpô.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VYU5MFLCCdxqp7h2ARxVrzyYQbr7GgHy
"""

#JOGO COM DOIS JOGADORES

class jokenpo:
  def __init__(self):
    self.opcoes = ["pedra", "tesoura", "papel"]
    self.jogador1 = ""
    self.jogador2 = ""




  def jogada(self):
    print("Escolha [1] para pedra, [2] para tesoura, [3] para papel")

  def verificar_resultado(self):
    if self.jogador1 == self.jogador2:
      print("Empate!")
    elif (
        (self.jogador1 == "pedra" and self.jogador2 == "tesoura") or
        (self.jogador1 == "tesoura" and self.jogador2 == "papel") or
        (self.jogador1 == "papel" and self.jogador2 == "pedra")
    ):
      print("Jogador 1 venceu!")
    else:
      print("Jogador 2 venceu!")

jogo = jokenpo()
jogo.jogada()


try:
  escolha_jogador1 = int(input("Jogador 1, escolha: "))
  if 1 <= escolha_jogador1 <= len(jogo.opcoes):
    jogo.jogador1 = jogo.opcoes[escolha_jogador1 - 1]
    print(f"Jogador 1 escolheu: {jogo.jogador1}")
  else:
    print("Escolha inválida para Jogador 1. Por favor, escolha 1, 2 ou 3.")
    jogo.jogador1 = None
except ValueError:
  print("Entrada inválida para Jogador 1. Por favor, digite um número.")
  jogo.jogador1 = None

try:
  escolha_jogador2 = int(input("Jogador 2, escolha: "))
  if 1 <= escolha_jogador2 <= len(jogo.opcoes):
    jogo.jogador2 = jogo.opcoes[escolha_jogador2 - 1]
    print(f"Jogador 2 escolheu: {jogo.jogador2}")
  else:
    print("numero invalido para Jogador 2")
    jogo.jogador2 = None
except ValueError:
  print("numero invalido para Jogador 2")
  jogo.jogador2 = None

if jogo.jogador1 is not None and jogo.jogador2 is not None:
  jogo.verificar_resultado()
else:
  print("o jogo não pôde ser concluído")

#JOGO COM COMPUTADOR
import random
import os

class JokePo:
    def __init__(self):
        self.pedra = "PEDRA"
        self.papel = "PAPEL"
        self.tesoura = "TESOURA"
        self.jogadas_validas = [self.pedra, self.papel, self.tesoura]

    def computador(self):
        return random.choice(self.jogadas_validas)

jogadas = JokePo()

while (True):
    os.system('cls')
    print("--- Jokenpô ---")
    print("Escolha: Pedra, Papel ou Tesoura")
    jogador = input("Sua jogada: ").upper()

    if jogador not in jogadas.jogadas_validas:
        print("\nJogada inválida!")
        input("Presine ENTER para continuar...\n")
        continue
    else:
        os.system('cls')
        computador_jogada = jogadas.computador()
        print(f"Sua jogada: {jogador}")
        print(f"Computador: {computador_jogada}")

        if jogador == computador_jogada:
            print("\nEMPATE!\n")
            break
        elif (
            (jogador == jogadas.pedra and computador_jogada == jogadas.tesoura) or
            (jogador == jogadas.papel and computador_jogada == jogadas.pedra) or
            (jogador == jogadas.tesoura and computador_jogada == jogadas.papel)
        ):
            print("\nVocê venceu!\n")
            break
        else:
            print("\nComputador venceu!\n")
            break

print("Encerrando.\n")