# -*- coding: utf-8 -*-
"""Preco da gasolina

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-lx8NWOWPclwf--w_ipPzM5N7fFJrKZa
"""

import pandas as pd
from google.colab import files
uploaded = files.upload()

import io
import pandas as pd


df = pd.read_csv("precos_gasolina_2_anos_sem_alinhamento.txt", sep=";")
print(df)

csv_sem_cabecalho = """2024-02;Aditivada;7.50
                       2025-04;Comum;6.51
                       2026-06;Premium;4.60"""

df_pessoas = pd.read_csv(io.StringIO(csv_sem_cabecalho), sep=";", header=None, names=["Mes", "Tipo", "Preco"])

df_pessoas.info()

print(df_pessoas.head(3))

df_so_nome = pd.read_csv(io.StringIO(csv_sem_cabecalho), header=None, usecols=[0])
print(df_so_nome)

df_pessoas = pd.read_csv(io.StringIO(csv_sem_cabecalho), sep=";", header=None, names=['CoLA', 'CoLB', 'CoLC'])
print(df_pessoas.head())

print(df_pessoas.shape)

"""DIFICIL"""

df_pessoas = pd.read_csv(io.StringIO(csv_sem_cabecalho), sep=";", header=None, names=['CoLA', 'CoLB', 'CoLC'], usecols=['CoLA', 'CoLB', 'CoLC'])
print(df_pessoas.head())

import pandas as pd
import io

csv_exer = """joao,25,engenheiro,20-32-2004
                      maria,30,arquiteta,21-34-2009
                      edu,20,pintor,05-15-1980
                      gus,38,filho.65-78-7654"""


df_exer = pd.read_csv(io.StringIO(csv_exer), sep=",", header=None, names=["nome", "idade", "profissao","Data"])
df_exer["Data"] = pd.to_datetime(df_exer["Data"], dayfirst=True, errors='coerce')
print(df_exer.dtypes)

from os import replace
import pandas as pd
import io
csv_exer2 = """r$300
r$400.00
r$250.00"""

df_valores = pd.read_csv(io.StringIO(csv_exer2), header=None, names=["valores"])
df_valores["valores"] = df_valores["valores"].str.replace('r$', '', regex=False)
df_valores["valores"] = pd.to_numeric(df_valores["valores"])
print(df_valores)