# -*- coding: utf-8 -*-
"""atividade.Hospital_2024_2025.csv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nUJngmGaY0I1T0Oh4BiI4FC4Xl2Qslwj
"""

import pandas as pd
from google.colab import files
uploaded = files.upload()

import pandas as pd


df_hospital = pd.read_csv("hospital_2024_2025.csv", sep=",")
print(df_hospital)

df = pd.read_csv("hospital_2024_2025.csv")
especialidade_series = df['especialidade'].squeeze()
print(type(especialidade_series))
print(especialidade_series)

# imprime os tipos de dados de cada columa no dataframe "df_hospital"
print(df_hospital.dtypes)
# imprime os nomes dos indices de cada item da lista comecando do zero do dataframe "df_hospital"
print(df_hospital.index)

Serie_Internacoes = df_hospital["internacoes"]
print(Serie_Internacoes)
type(Serie_Internacoes)

print(df_hospital.dtypes)

print(df.info())

dados = {
    'index': ['1', '2', '3']
}


index = ['a', 'b', 'c']

df_personalizado = pd.DataFrame(dados, index=index)
print(df_personalizado)

medico = {"CRM": 123, "nome": "Carlos", "specialidade": "pediatra"}
print(medico)

print(df_hospital.values)