# -*- coding: utf-8 -*-
"""atividade1.python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B9w3781nBvBTjsIFS8GZl3OuAnGXmGqO

FACIL
"""

# importa uma biblioteca de pandas
import pandas as pd

# cria uma lista de dicionarios
# as chaves "Aluno" e "Nota" serao os nomes das colunas
# os valores sao listas que representao os dados de cada columa
dados = {
    "Aluno":["Joao","Maria"],
    "Nota":[8, 9],
}

# converte o dataframe em um dicionario de pandas
df_escola = pd.DataFrame(dados)
# imprime os dados
print(df_escola)

# cria uma serie de pandas chamada "Vendas"
minha_serie = pd.Series([100, 200, 300], name = "vendas")
# imprime a lista
print(minha_serie)

# imprime os tipos de dados de cada columa no dataframe "df_escola"
print(df_escola.dtypes)
# imprime os nomes dos indices de cada item da lista comecando do zero do dataframe "df_escola"
print(df_escola.index)

"""INTERMEDIARIO"""

# cria uma lista simples
dados = [
    ['Celular', 1500],
    ['tablet', 800]
]

# converte um dataframe em um dicionario de pandas
df_lista = pd.DataFrame(dados, columns=['Produto', 'Preco'])
# cada chave vira uma columa e cada posicao da lista vira uma linha
print(df_lista)

# extrai a coluna "Nota" e guarda em uma variavel
Serie_Nota = df_escola["nota"]
#imprime os dados e o tipo da variavel
print(Serie_Nota)

# cria uma columa com numeros decimais e verifica se o pandas identificou como float64
df_decimais = pd.DataFrame({"valores": [1.5, 2.7]})
print(df_decimais)

"""DIFICIL"""

# cria uma lista numerica que tenha um texto escrito
dados = {
  "idade":[1, 2, 3, "ssss"]
}

# verifica o dtype dessa coluna e verifica se o pandas identificou como object ou int
df_intruso = pd.DataFrame(dados)
print(df_intruso.dtypes)
print(df_intruso.index)

# importa a biblioteca pandas
import pandas as pd

# criar uma lista de dicionarios
dados = {
    'index': ['1', '2', '3']
}

# personaliza a lista "index" e transforma ela
index = ['a', 'b', 'c']

df_personalizado = pd.DataFrame(dados, index=index)
print(df_personalizado)

# a quantidade de items na lista "Nomes" é maior do que na lista "Idades", o que resulta no erro, ja que todos os arrays devem ter o mesmo comprimento.
dados = {
  "Nomes":["du", "dudu", "edu"],
  "idades":[1, 2, 3, 4]
}

df_ddd = pd.DataFrame(dados)
print(df_ddd)

# imprime o valor bruto
print(df_escola.values)